language: java

jdk:
  - oraclejdk8
  - oraclejdk7

before_script:
  - ./gradlew check
  -  ./gradlew assemble

script:
  - jdk_switcher use oraclejdk8
  - ./gradlew test --tests "*Test"
  - jdk_switcher use oraclejdk7
  - ./gradlew test --tests "*Test"

